# Generated by Django 3.1 on 2020-09-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='default_address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
