# Generated by Django 3.1 on 2020-08-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stores',
            new_name='Store',
        ),
    ]
