# Generated by Django 3.1 on 2020-08-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select_store', '0002_auto_20200812_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='name',
        ),
    ]
