# Generated by Django 3.1 on 2020-09-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_store', '0003_auto_20200812_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
