# Generated by Django 3.1 on 2020-08-31 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('select_store', '0003_auto_20200812_2021'),
        ('checkout', '0003_remove_order_town_or_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='select_store.store'),
        ),
    ]
