# Generated by Django 3.1 on 2020-09-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200831_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='NEW', max_length=20, null=True),
        ),
    ]
