# Generated by Django 3.1 on 2020-09-15 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('select_store', '0004_auto_20200906_2230'),
        ('checkout', '0009_remove_order_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='select_store.store'),
        ),
    ]
