# Generated by Django 3.1 on 2020-09-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20200915_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='customizations',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='size',
            field=models.CharField(default='Regular', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
