# Generated by Django 3.1 on 2020-08-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
