# Generated by Django 3.1 on 2020-08-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pizza_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sku',
            field=models.CharField(max_length=254),
        ),
    ]
