# Generated by Django 3.1 on 2020-09-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_delete_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='product_type',
        ),
    ]
