# Generated by Django 3.1 on 2020-09-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200907_1423'),
        ('menu', '0007_auto_20200907_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Pizza',
        ),
    ]
