# Generated by Django 3.1 on 2020-09-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200907_1423'),
        ('menu', '0008_auto_20200907_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='Product',
        ),
    ]
