# Generated by Django 3.1 on 2020-09-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20200907_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppingamount',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_amounts', to='menu.product'),
        ),
        migrations.AlterField(
            model_name='toppingamount',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_amounts', to='menu.topping'),
        ),
    ]
