# Generated by Django 3.1 on 2020-09-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20200907_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
