# Generated by Django 3.1 on 2020-09-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_product_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
