# Generated by Django 3.1 on 2020-10-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
